import os
import sys
from datetime import datetime
from fpdf import FPDF

class ApexLetterheadPDF(FPDF):
    def __init__(self, logo_path, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.logo_path = logo_path

    def header(self):
        # Top-most colorful accent strip (Premium styling)
        self.set_fill_color(11, 37, 64) # Navy Blue (#0B2540)
        self.rect(0, 0, 105, 3.5, 'F')
        self.set_fill_color(0, 163, 166) # Technical Teal (#00A3A6)
        self.rect(105, 0, 105, 3.5, 'F')

        # Company Logo rendering
        if os.path.exists(self.logo_path):
            # Placing the horizontal logo on the top-left (approx 1.68 aspect ratio)
            # 35mm width means height is ~20.8mm.
            self.image(self.logo_path, 15, 10, 35)
        
        # Header Right - Company Brand Typography
        self.set_font("helvetica", "B", 15)
        self.set_text_color(11, 37, 64) # Deep Navy
        self.set_xy(55, 11)
        self.cell(0, 6, "APEX TECH SOFTWARE INSTITUTE", ln=True, align="R")
        
        self.set_font("helvetica", "I", 9.5)
        self.set_text_color(0, 163, 166) # Technical Teal
        self.set_x(55)
        self.cell(0, 5, "Empowering Careers, Creating Industry Leaders", ln=True, align="R")
        
        self.set_font("helvetica", "", 8)
        self.set_text_color(100, 116, 139) # Slate-500
        self.set_x(55)
        self.cell(0, 4.5, "Regd. No. TS/HYD/1094/2026  |  ISO 9001:2015 Certified  |  A Grade Accredited", ln=True, align="R")
        
        # Dual-Colored Horizontal Accent Bar
        self.set_line_width(0.8)
        self.set_draw_color(11, 37, 64) # Navy Left
        self.line(15, 34, 135, 34)
        self.set_draw_color(0, 163, 166) # Teal Right
        self.line(135, 34, 195, 34)
        
        # Margin Spacing for Letterhead Content Area
        self.set_y(40)

    def footer(self):
        # Position at 22mm from bottom
        self.set_y(-22)
        
        # Technical Split Divider Line
        self.set_line_width(0.4)
        self.set_draw_color(226, 232, 240) # Light Slate
        self.line(15, self.get_y(), 195, self.get_y())
        
        # Footer Content Rows
        self.set_y(-18)
        self.set_font("helvetica", "B", 7.5)
        self.set_text_color(71, 85, 105) # Slate-700
        self.cell(90, 4, "CAMPUS ADDRESS:", ln=False)
        self.cell(45, 4, "TELEPHONE / HR:", ln=False)
        self.cell(0, 4, "DIGITAL CHANNELS:", ln=True, align="R")
        
        self.set_font("helvetica", "", 7.5)
        self.set_text_color(100, 116, 139) # Slate-500
        self.cell(90, 4, "Pillar No. 12, Kondapur Main Road, Hyderabad - 500084, TS", ln=False)
        self.cell(45, 4, "+91 8977696937  |  hr@apextech.com", ln=False)
        self.cell(0, 4, "www.apextechsoftwareinstitute.com", ln=True, align="R")
        
        # Decorative Bottom Band
        self.set_fill_color(11, 37, 64)
        self.rect(0, 292.5, 210, 4.5, 'F') # Standard A4 Height is 297mm
        
        self.set_xy(15, -9)
        self.set_font("helvetica", "I", 7)
        self.set_text_color(148, 163, 184) # Slate-400
        self.cell(0, 3, "This is an authentic document generated by Apex Tech Software Institute. All rights reserved.", align="C")

def generate_official_letterhead(output_path, logo_path):
    print(f"Initializing letterhead generation...")
    print(f"Logo Path: {logo_path}")
    print(f"Output Path: {output_path}")

    # Standard A4 PDF Setup (Margins: Left=15mm, Right=15mm)
    pdf = ApexLetterheadPDF(logo_path=logo_path, orientation="P", unit="mm", format="A4")
    pdf.set_margins(15, 40, 15)
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # ----------------------------------------------------
    # DOCUMENT CONTENT (Official Letter Template)
    # ----------------------------------------------------
    
    # 1. Letter Metadata Info Row
    pdf.set_y(44)
    pdf.set_font("helvetica", "B", 9)
    pdf.set_text_color(71, 85, 105) # Slate-600
    pdf.cell(100, 5, "Ref No: ATSI/CORP-OFFER/2026/492", ln=False)
    
    current_date = datetime.now().strftime("%B %d, %Y")
    pdf.set_font("helvetica", "B", 9)
    pdf.cell(0, 5, f"Date: {current_date}", ln=True, align="R")
    
    # Spacing
    pdf.ln(8)
    
    # 2. Recipient Block
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(15, 23, 42) # Slate-900
    pdf.cell(0, 5, "To,", ln=True)
    
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 5, "The Training & Placement Directorate,", ln=True)
    pdf.set_font("helvetica", "", 10)
    pdf.cell(0, 5, "Partner Engineering & Science Colleges,", ln=True)
    pdf.cell(0, 5, "Hyderabad Region, Telangana, India.", ln=True)
    
    pdf.ln(6)
    
    # 3. Subject Line
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(11, 37, 64) # Navy Blue
    pdf.cell(0, 6, "Subject: Official Collaboration for Industry-Ready IT Training & Direct Placement Drive 2026-27", ln=True)
    
    # Solid decorative bar under subject
    pdf.set_fill_color(0, 163, 166) # Technical Teal
    pdf.rect(15, pdf.get_y() + 1, 180, 0.4, 'F')
    
    pdf.ln(6)
    
    # 4. Salutation
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 5, "Dear Director / Placement Officer,", ln=True)
    
    pdf.ln(4)
    
    # 5. Core Body Paragraphs
    pdf.set_font("helvetica", "", 9.5)
    pdf.set_text_color(51, 65, 85) # Slate-700
    
    p1 = (
        "We are pleased to introduce Apex Tech Software Institute (ATSI) as Hyderabad's leading "
        "specialized technical training academy. Located in the IT hub of Kondapur, Hyderabad, "
        "ATSI provides world-class, project-oriented, and placement-driven educational programs "
        "in Advanced AWS & DevOps, SAP ERP Enterprise Core, Full-Stack Web Development, Data Science & AI, "
        "and Salesforce Administration. Our goal is to bridge the gap between academic theory and active "
        "industry requirements, transforming graduates into immediate, highly-productive assets for global IT firms."
    )
    pdf.multi_cell(180, 5, p1)
    pdf.ln(4)
    
    p2 = (
        "Under this formal correspondence, we offer your final-year students special access to our "
        "comprehensive Technical Bootcamp, which features live lab infrastructure, direct expert mentorship, "
        "industry certification guidance, and mock interviews. Additionally, students registered through this "
        "collaborative framework are directly fast-tracked to our premium CRM recruitment pool, gaining "
        "unlimited interview schedules with our network of over 150+ actively hiring global tech partners."
    )
    pdf.multi_cell(180, 5, p2)
    pdf.ln(5)
    
    # 6. Highlights Bullet Points Box (Beautiful visual list)
    pdf.set_fill_color(248, 250, 252) # Light Slate Box Background
    pdf.set_draw_color(226, 232, 240)
    pdf.rect(15, pdf.get_y(), 180, 32, 'DF')
    
    pdf.set_y(pdf.get_y() + 2)
    pdf.set_x(18)
    pdf.set_font("helvetica", "B", 9)
    pdf.set_text_color(11, 37, 64)
    pdf.cell(0, 5, "Key Partnership Highlights & Outcomes:", ln=True)
    
    pdf.set_font("helvetica", "", 8.5)
    pdf.set_text_color(71, 85, 105)
    
    bullets = [
        "  -  Curriculum designed, refined, and delivered exclusively by active Senior IT Professionals.",
        "  -  Comprehensive hands-on labs with dedicated servers and real-world project portfolios.",
        "  -  In-depth Resume Building, LinkedIn optimization, and 1-on-1 Interview Coaching.",
        "  -  Direct on-campus placement drives and corporate hiring referrals with 100% assistance."
    ]
    for bullet in bullets:
        pdf.set_x(18)
        pdf.cell(0, 4.5, bullet, ln=True)
        
    pdf.set_y(pdf.get_y() + 6)
    
    p3 = (
        "We look forward to hosting an on-campus seminar or interactive workspace session with your "
        "students to discuss future career growth and demonstrate our real-time cloud and SAP environments. "
        "Please feel free to connect with our institutional relations coordinator directly at +91 8977696937 or via "
        "email at corporate@apextechsoftwareinstitute.com to schedule a convenient date."
    )
    pdf.multi_cell(180, 5, p3)
    pdf.ln(6)
    
    p_close = "Thanking you and assuring you of our highest professional standards at all times."
    pdf.multi_cell(180, 5, p_close)
    pdf.ln(8)
    
    # 7. Signature Block
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 5, "For Apex Tech Software Institute,", ln=True)
    
    pdf.ln(10) # Spacing for manual signature/stamp
    
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(11, 37, 64)
    pdf.cell(0, 5, "Sai Charan Mamidi", ln=True)
    
    pdf.set_font("helvetica", "", 9.5)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 4.5, "Managing Director & Academic Dean", ln=True)
    pdf.cell(0, 4, "Apex Tech Software Institute, Hyderabad", ln=True)

    # Make parent directory if not exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    # Save Output
    pdf.output(output_path)
    print(f"SUCCESS: Letterhead PDF successfully generated and saved to: {output_path}")

if __name__ == "__main__":
    # Default Paths
    default_output = "/home/sathish/Desktop/apex/public/apex-letterhead.pdf"
    default_logo = "/home/sathish/Desktop/apex/public/logo.png"
    
    # Allow command line overrides
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    logo = sys.argv[2] if len(sys.argv) > 2 else default_logo
    
    generate_official_letterhead(output, logo)
